# Generated by Django 4.1.1 on 2022-10-12 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='disliked',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='liked',
        ),
    ]
