# Generated by Django 4.1.1 on 2022-10-12 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_choices_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='choices_wishlist',
        ),
    ]
