# Generated by Django 4.1.1 on 2022-10-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment_choices_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='choices_wishlist',
        ),
        migrations.AddField(
            model_name='blog',
            name='choices_wishlist',
            field=models.CharField(choices=[('liked', 1), ('disliked', 0)], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
