# Generated by Django 4.1.1 on 2022-10-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_comment_choices_wishlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='choices_wishlist',
            field=models.CharField(blank=True, choices=[('disliked', 0), ('liked', 1)], max_length=10, null=True),
        ),
    ]
