# Generated by Django 4.1.1 on 2022-10-22 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blog_choices_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childern', to='blog.comment'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='choices_wishlist',
            field=models.CharField(blank=True, choices=[('liked', 'liked'), ('disliked', 'disliked')], max_length=10, null=True),
        ),
    ]
