# Generated by Django 4.1.1 on 2022-10-23 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0011_rename_comment_comment_comment_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_text',
        ),
        migrations.AlterField(
            model_name='blog',
            name='choices_wishlist',
            field=models.CharField(blank=True, choices=[('disliked', 'disliked'), ('liked', 'liked')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='TextComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_comments', to='blog.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
