# Generated by Django 4.1.1 on 2022-10-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_comment_comment_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textcomment',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='choices_wishlist',
            field=models.CharField(blank=True, choices=[('liked', 'liked'), ('disliked', 'disliked')], max_length=10, null=True),
        ),
    ]
