# Generated by Django 4.1.1 on 2022-10-23 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_textcomment_text_alter_blog_choices_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_text',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments_text', to='blog.comment'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TextComment',
        ),
    ]
